server:
  port: 8082

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: planning-service
          uri: http://localhost:8081
          predicates:
            - Path=/planning/**
        - id: calendar-service
          uri: http://localhost:8080
          predicates:
            - Path=/calendrier-sports/**
        - id: sites-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/sites/**
