server:
  port: 8082

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      - id: planning-service
        uri: http://localhost:8081
        predicates:
          - Path=/planning/**
      - id: calendar-service
        uri: http://localhost:8080
        predicates:
          - Path=/calendar/**
      - id: sites-service
        uri: http://localhost:8083
        predicates:
          - Path=/sites/**
